### ISSUE TITLE
Move VLC binaries to repo

### ISSUE THREAD

**Issue by kowdermeister** [beresmate/nodeselekta#1]
It would make sense to distribute the app with the recommended, tested VLC player. 
legally, no problem: http://www.videolan.org/legal.html

**Comment by kowdermeister** [comment]
Just don't forget about the "headless" version for Raspberry PI applications. I'm not sure about legit use cases for media servers, I never had one.

**Comment by beresmate** [comment]
see the build specific ticket: https://github.com/beresmate/nodeselekta/issues/7

**Comment by kowdermeister** [comment]
Build/release script will download it.
